apiVersion: v1
kind: Service
metadata:
  name: db
  label:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPost: 5432
  selector:
     name: postgres-pod
     app: demo-voting-app 
